# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-19 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom_relation',
            name='time_record',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
