# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesting', '0007_indentity_symptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indentity_symptom',
            name='NIS',
        ),
        migrations.AlterField(
            model_name='symptom_relation',
            name='Unique_Identity',
            field=models.ManyToManyField(related_name='symptom', to='nesting.Identity_unique'),
        ),
        migrations.DeleteModel(
            name='Indentity_Symptom',
        ),
    ]
